### ISSUE TITLE
Nobody with appropriate permissions to support django-configurations project

### ISSUE THREAD

**Issue by uhurusurfa** [jazzband-roadies/help#378]
We are trying to update the django-configurations project but cannot contact anyone who has appropriate permissions.

Please let me know who I can contac t to add people with full permissions to the project.

Thanks

**Comment by uhurusurfa** [comment]
Adding @pauloxnet

**Comment by jezdez** [comment]
Please link to the original issues next time: https://github.com/jazzband/django-configurations/pull/392 This is now fixed.

**Comment by uhurusurfa** [comment]
@jezdez Thank you

**Comment by uhurusurfa** [comment]
@jezdez - can you review settings for @pauloxnet as he still does not have maintain er permissions and I would like to request being added to the same project with equivalent permissions (there is no reference to this project in jazzband.io for me to request through that route).

Thank you

**Comment by jezdez** [comment]
@uhurusurfa I'm not sure I follow, @pauloxnet and @blueyed are project leads and maintainers, see https://jazzband.co/projects/django-configurations and:

![CleanShot 2024-11-13 at 19 23 51@2x](https://github.com/user-attachments/assets/14dbd4fd-1ca2-484c-b1b2-5c34b26d01cd)

What permissions are currently missing specifically?

Project leads are usually reserved for people with a proven track record with a project, since they are also able to release new updates to PyPI. Feel free to open a new ticket to make that case, in case you want to become a project lead.

**Comment by jezdez** [comment]
Oh, I see there is already #379, nice!
